version: '3.3'

services:
    frontend:
        build: ./example-frontend
        ports:
            - 5000:5000
        container_name: frontend

    backend:
        build: ./example-backend
        ports:
            - 8080:8080
        environment:
            - REDIS_HOST=redis
        container_name: backend

    redis:
        image: redis
