version: '3.3'

services:
    simple-web-service:
        image: devopsdockeruh/simple-web-service
        volumes: 
            - ./log.txt:/usr/src/app/text.log
        container_name: simpler-web-log
