version: '3.3'

services:
    simple-web-server:
        image: devopsdockeruh/simple-web-service
        ports:
            - 8080:8080
        command: server
        container_name: simple-webserver
