#Fetching required image
FROM ubuntu:20.04

#Install curl
RUN apt update && apt install curl -y

#Setting up work directory
WORKDIR usr/src/app

#Copy script
COPY ~/script.sh .

#Command to run the script
CMD ./script.sh
